# Taille de la fenêtre
WINDOW_WIDTH = 1300
WINDOW_HEIGHT = 700

# Taille de Sketchpad
CANVAS_SIZE = 500
CANVAS_X = 100
CANVAS_Y = (WINDOW_HEIGHT - CANVAS_SIZE) // 2

# Taille de Graph 
GRAPH_SIZE = 550
GRAPH_X = CANVAS_X + CANVAS_SIZE + 50
GRAPH_Y = CANVAS_Y - (GRAPH_SIZE - CANVAS_SIZE)//2

BLEUE_CIEL = "#00c8ff"